name: Deploy to Ubuntu Server

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    # 코드 체크아웃
    - name: Checkout repository
      uses: actions/checkout@v2

    # JDK 17 설정
    - name: Set up JDK 17
      uses: actions/setup-java@v1
      with:
        java-version: '17'

    # gradlew 권한 설정
    - name: Set gradlew permissions
      run: chmod +x ./gradlew

    # Gradle 빌드 (테스트 제외)
    - name: Build with Gradle
      run: ./gradlew clean build -x test

    # SSH 키 설정
    - name: Set SSH key permissions
      run: |
        mkdir -p ~/.ssh
        echo "${{ secrets.SERVER_SSH_KEY }}" > ~/.ssh/id_ed25519
        chmod 600 ~/.ssh/id_ed25519

    - name: Add SSH key
      uses: webfactory/ssh-agent@v0.5.3
      with:
        ssh-private-key: ${{ secrets.SERVER_SSH_KEY }}

    - name: Add known_hosts
      run: ssh-keyscan -t ed25519 3.26.223.215 >> ~/.ssh/known_hosts

    # WAR 파일 서버로 배포
    - name: Deploy to Server with rsync
      run: |
        rsync -avz -e "ssh -o StrictHostKeyChecking=no" build/libs/*.war ubuntu@3.26.223.215:/home/ubuntu/app

    # 서버에서 실행
    - name: Run SSH commands
      run: |
        ssh -i ~/.ssh/id_ed25519 ubuntu@3.26.223.215 << 'EOF'
          pkill -f 'java -jar' || true
          nohup java -jar /home/ubuntu/app/*-0.0.1-SNAPSHOT.war > /home/ubuntu/app/app.log 2>&1 &
        EOF
